apiVersion: apps/v1
kind: Deployment
# metadata contains the labels
metadata:
  namespace: default
  name: backend-deployment
  labels:
      app: backend  # this label is used by the serivce
# sepcification contains the selectors
spec:
  replicas: 1
  # match all the labels of pods
  selector:
    matchLabels:
      app: backend
  # template = blueprint for the pods
  template:
      # specification of codehub pod with its own metadata and spec
    metadata:
      labels:
        app: backend  # this label is used by the service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: backend-image
          image: 750096361451.dkr.ecr.us-east-1.amazonaws.com/terraform-eks-demo-backend # automatically attaches image with latest tag
          imagePullPolicy: Always
          resources:
           limits:
             memory: "200Mi"
             cpu: "100m"
           requests:
             memory: "100Mi"
             cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend  # deployment and pod labels
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000 # port in which the container codehub is running on
  